name: hopyn
description: A Flutter-based Uber clone UI with clean architecture and Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_maps_flutter: ^2.3.0
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/hopyn_logo.png"
